---
# - name: 'lesmyrmidons.mongodb'
#   src: 'https://github.com/lesmyrmidons/ansible-role-mongodb.git'
#   version: 'master'
#
- name: 'elastic.elasticsearch'
  src: 'https://github.com/elastic/ansible-elasticsearch.git'
  version: 'master'

- name: 'jdauphant.nginx'
  src: 'https://github.com/jdauphant/ansible-role-nginx.git'
  version: 'v2.7.4'

- name: 'SoInteractive.mongodb'
  version: '0.1.4'
